"""Generate the Dart test fixture from the real Micro Plan workbook.

- Staff rows (6-11: names and mobile numbers of the team) are dropped.
- Contact person / contact number are anonymised, keeping what the parser
  checks: blank stays blank, 0 stays 0, other numbers keep their digit count.
- Expected results come from micro_plan_ref.py (the Python reference rules).
"""
import datetime
import re
import sys

import openpyxl

import micro_plan_ref as ref

SRC = sys.argv[1]
OUT_FIXTURE = sys.argv[2]
OUT_EXPECTED = sys.argv[3]

STAFF_ROWS = range(6, 12)  # 1-based, inclusive of 11
CONTACT_PERSON_COL = 11  # K, 1-based
CONTACT_NUMBER_COL = 12  # L, 1-based


def dart_str(s):
    s = (s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
         .replace('\n', '\\n').replace('\r', '\\r'))
    return "'" + s + "'"


def dart_value(v):
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, datetime.datetime):
        return f'DateTime({v.year}, {v.month}, {v.day})'
    return dart_str(str(v))


def anonymise(col, v):
    if v is None:
        return None
    if col == CONTACT_PERSON_COL:
        return 'CONTACT PERSON' if str(v).strip() else v
    if col == CONTACT_NUMBER_COL:
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            n = int(v)
            if n == 0:
                return 0
            return int('5' * len(str(abs(n))))
        s = str(v)
        return re.sub(r'\d', '5', s)
    return v


def camel(flag):
    parts = flag.lower().split('_')
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])


wb = openpyxl.load_workbook(SRC, data_only=True)
out = []
out.append('// GENERATED from the real 2025-26 Micro Plan workbook by')
out.append('// tool/micro_plan/gen_fixture.py. Do not edit by hand.')
out.append('//')
out.append('// Staff rows (6-11) are removed and contact person / number are')
out.append('// anonymised; everything the parser reads is otherwise as in the file.')
out.append("import 'package:referredline/domain/services/micro_plan/micro_plan_models.dart';")
out.append('')
out.append('final List<MicroPlanSheetInput> realPlan2025Sheets = [')
for ws in wb.worksheets:
    last = 0
    for r in range(1, min(ws.max_row, 400) + 1):
        if any(ws.cell(r, c).value not in (None, '') for c in range(1, 15)):
            last = r
    out.append('  MicroPlanSheetInput(')
    out.append(f'    name: {dart_str(ws.title)},')
    out.append('    rows: [')
    for r in range(1, last + 1):
        if r in STAFF_ROWS:
            out.append('      [],')
            continue
        vals = [anonymise(c, ws.cell(r, c).value) if r >= ref.FIRST_DATA_ROW
                else ws.cell(r, c).value for c in range(1, 15)]
        while vals and vals[-1] is None:
            vals.pop()
        out.append('      [' + ', '.join(dart_value(v) for v in vals) + '],')
    out.append('    ],')
    out.append('    merges: [')
    for m in sorted(ws.merged_cells.ranges, key=lambda m: (m.min_row, m.min_col)):
        if m.min_row in STAFF_ROWS or m.max_row in STAFF_ROWS:
            continue
        if m.min_row > last:
            continue
        out.append(
            f'      const MicroPlanMerge(firstRow: {m.min_row}, lastRow: {m.max_row}, '
            f'firstColumn: {m.min_col}, lastColumn: {m.max_col}),')
    out.append('    ],')
    out.append('  ),')
out.append('];')
open(OUT_FIXTURE, 'w').write('\n'.join(out) + '\n')

exp = []
exp.append('// GENERATED by tool/micro_plan/gen_fixture.py from the Python reference')
exp.append('// rules (tool/micro_plan/micro_plan_ref.py). One line per data row:')
exp.append('// sheet|row|kind|date|flags (flags sorted).')
exp.append('const List<String> realPlan2025ExpectedRows = [')
for ws in wb.worksheets:
    for row in ref.parse_sheet(ws):
        flags = ','.join(sorted(camel(f) for f in row['flags']))
        exp.append('  ' + dart_str(
            f"{ws.title}|{row['row']}|{row['kind'].lower()}|{row['date'] or '-'}|{flags}") + ',')
exp.append('];')
open(OUT_EXPECTED, 'w').write('\n'.join(exp) + '\n')
print('ok')
